name: pybullet_fingers
channels:
- anaconda
- conda-forge
dependencies:
- python=3.6.9
- numpy==1.18.1
- pinocchio==2.3.1
- pip==20.1.1
- pip:
  - pybullet==2.8.1
  - gym==0.17.2
  - tensorflow==1.14.0
  - namegenerator==1.0.6
  - mpi4py==3.0.3
  - joblib==0.15.1
  - opencv-python==4.2.0.34
  - catkin-pkg==0.4.20
